In [17]:
#PASO 1: CARGA DEl DATASET ZONAS

import pandas as pd
import os

# Configuración de rutas
ruta_tablas = '../../datos/base_datos'
pd.set_option('display.max_columns', None)

# 1.1 Carga de la tabla maestra de Zonas (la base de las 31 filas)
df_zonas = pd.read_csv(os.path.join(ruta_tablas, 'zonas', 'ZONAS.csv'))

# 1.2 Visualización previa 
print("-" * 70)
print("📊 Previsualización de ZONAS:")
print("-" * 70)
display(df_zonas.head())

# 1.3 Filtramos las columnas necesarias
# Mantenemos ID_ZONA, NOMBRE_ZONA y AREA_KM2
df_zonas = df_zonas[['ID_ZONA', 'NOMBRE_ZONA', 'AREA_KM2']].copy()

# 1.4 Verificación
print("-" * 70)
print(f"✅ Tabla ZONAS lista (Base del Master). Filas: {df_zonas.shape[0]}")
print("-" * 70)
display(df_zonas.head())

----------------------------------------------------------------------
📊 Previsualización de ZONAS:
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,NOMBRE_DISTRITO,AREA_KM2
0,MN0101,Financial District-Battery Park City,Manhattan,19.2268
1,MN0102,Tribeca-Civic Center,Manhattan,13.5782
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,Manhattan,11.9933
3,MN0201,SoHo-Little Italy-Hudson Square,Manhattan,12.9168
4,MN0202,Greenwich Village,Manhattan,10.6005

----------------------------------------------------------------------
✅ Tabla ZONAS lista (Base del Master). Filas: 38
----------------------------------------------------------------------

  ID_ZONA                                        NOMBRE_ZONA  AREA_KM2
0  MN0101               Financial District-Battery Park City   19.2268
1  MN0102                               Tribeca-Civic Center   13.5782
2  MN0191  The Battery-Governors Island-Ellis Island-Libe...   11.9933
3  MN0201                    SoHo-Little Italy-Hudson Square   12.9168
4  MN0202                                  Greenwich Village   10.6005

In [18]:
#PASO 2: CARGA Y SELECCIÓN DEL DATASET CENSO

# 2.1 Carga del dataset
df_censo = pd.read_csv(os.path.join(ruta_tablas, 'censo', 'CENSO.csv'))

# 2.2 Visualización previa 
print("-" * 70)
print("📊 Previsualización de CENSO:")
print("-" * 70)
display(df_censo.head(3))

# 2.3 Selección de las variables 
columnas_finales_censo = [
    'ID_ZONA', 
    'POBLACION_TOTAL', 
    'EDAD_MEDIANA', 
    'INGRESO_MEDIANO_HOGAR', 
    'TASA_EMPLEO', 
    'TAMANO_HOGAR_PROMEDIO', 
    'POBLACION_HISPANA',
    'TASA_OCUPACION'
]
df_censo_sel = df_censo[columnas_finales_censo].copy()

# 2.4 Unión al Master (Filtro por ID_ZONA)
# Aquí es donde el Master se queda con las 31 zonas válidas de Manhattan
df_master = pd.merge(df_zonas, df_censo_sel, on='ID_ZONA', how='left')

print("-" * 70)
print(f"✅ CENSO integrado. Dimensiones del Master: {df_master.shape}")
print("-" * 70)
display(df_master.head())

----------------------------------------------------------------------
📊 Previsualización de CENSO:
----------------------------------------------------------------------

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION
0,MN0101,48608,34.3,198961.0,79.57,1.99,1639,83.10
1,MN0102,23257,36.8,185902.0,68.92,2.20,873,81.41
2,MN0201,22167,39.3,132900.0,70.97,1.78,975,82.01

----------------------------------------------------------------------
✅ CENSO integrado. Dimensiones del Master: (38, 10)
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61

In [19]:
#PASO 3: CARGA Y SELECCIÓN DEL DATASET SEGURIDAD

# 3.1 Carga del dataset
df_seguridad = pd.read_csv(os.path.join(ruta_tablas, 'seguridad', 'SEGURIDAD.csv'))

# 3.2 Visualización previa
print("-" * 70)
print("📊 Previsualización de SEGURIDAD:")
print("-" * 70)
display(df_seguridad.head(15))

# 3.3 Definición de la lógica de subclasificación por entorno
def clasificar_entorno_riesgo(row):
    # Riesgo directo al local: Ocurre en comercio o es específicamente robo a establecimiento
    if row['LUGAR_DELITO'] == 'LOCAL COMERCIAL' or row['TIPO_DELITO'] == 'ROBO A ESTABLECIMIENTO':
        return 'SEG_DELITOS_PROPIEDAD'
    # Riesgo en el trayecto: Ocurre en el sistema de transporte
    elif row['LUGAR_DELITO'] == 'TRANSPORTE':
        return 'SEG_DELITOS_TRANSPORTE'
    # Riesgo de entorno general: Vía pública, edificios, etc.
    else:
        return 'SEG_DELITOS_OTROS'

# 3.4 Aplicamos la clasificación
df_seguridad['SUB_CATEGORIA'] = df_seguridad.apply(clasificar_entorno_riesgo, axis=1)

# 3.5 Agregación pivotada por ID_ZONA y SUB_CATEGORIA
df_seg_agrupado = df_seguridad.groupby(['ID_ZONA', 'SUB_CATEGORIA'])['CANTIDAD_INCIDENTES'].sum().unstack(fill_value=0).reset_index()

# 3.6 TRATAMIENTO DE ENTEROS
columnas_seg = ['SEG_DELITOS_PROPIEDAD', 'SEG_DELITOS_TRANSPORTE', 'SEG_DELITOS_OTROS']
for col in columnas_seg:
    if col in df_seg_agrupado.columns:
        df_seg_agrupado[col] = df_seg_agrupado[col].astype(int)

# 3.7 Limpieza de seguridad previa en el master (para evitar duplicidad o columnas viejas)
columnas_a_limpiar = ['TOTAL_DELITOS', 'SEG_DELITOS_PROPIEDAD', 'SEG_DELITOS_TRANSPORTE', 'SEG_DELITOS_OTROS']
for col in columnas_a_limpiar:
    if col in df_master.columns:
        df_master = df_master.drop(columns=[col])

# 3.7 Unión al Master
df_master = pd.merge(df_master, df_seg_agrupado, on='ID_ZONA', how='left')

print("-" * 70)
print(f"✅ SEGURIDAD integrada.. Dimensiones del Master: {df_master.shape}")
print("-" * 70)
display(df_master.head())

----------------------------------------------------------------------
📊 Previsualización de SEGURIDAD:
----------------------------------------------------------------------

   ID_ZONA             TIPO_DELITO        LUGAR_DELITO  CANTIDAD_INCIDENTES
0   MN0101            ASALTO GRAVE  EDIFICIOS PUBLICOS                    6
1   MN0101            ASALTO GRAVE     LOCAL COMERCIAL                    7
2   MN0101            ASALTO GRAVE               OTROS                    6
3   MN0101            ASALTO GRAVE          TRANSPORTE                   18
4   MN0101            ASALTO GRAVE         VIA PUBLICA                   23
5   MN0101            ASALTO GRAVE    ZONA RESIDENCIAL                    4
6   MN0101  ROBO A ESTABLECIMIENTO     LOCAL COMERCIAL                   26
7   MN0101  ROBO A ESTABLECIMIENTO               OTROS                    9
8   MN0101  ROBO A ESTABLECIMIENTO         VIA PUBLICA                    1
9   MN0101  ROBO A ESTABLECIMIENTO    ZONA RESIDENCIAL                    9
10  MN0101      ROBO CON VIOLENCIA     LOCAL COMERCIAL                   26
11  MN0101      ROBO CON VIOLENCIA               OTROS                   10
12  MN0101      ROBO CON VIOLENCIA          TRANSPORTE                   10
13  MN0101      ROBO CON VIOLENCIA         VIA PUBLICA                   22
14  MN0101      ROBO CON VIOLENCIA    ZONA RESIDENCIAL                    2

----------------------------------------------------------------------
✅ SEGURIDAD integrada.. Dimensiones del Master: (38, 13)
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,SEG_DELITOS_OTROS,SEG_DELITOS_PROPIEDAD,SEG_DELITOS_TRANSPORTE
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10,73.0,78.0,28.0
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41,116.0,77.0,13.0
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01,88.0,116.0,6.0
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61,93.0,80.0,16.0

In [20]:
#PASO 4: CARGA Y SELECCIÓN DEL DATASET MOVILIDAD

# 4.1 Carga del dataset
df_movilidad = pd.read_csv(os.path.join(ruta_tablas, 'movilidad', 'MOVILIDAD.csv'))

# 4.2 Visualización previa 
print("-" * 70)
print("📊 Previsualización de MOVILIDAD:")
print("-" * 70)
display(df_movilidad.head(3))
display(df_movilidad.info())

# 4.3 Agregación de datos por ID_ZONA
df_semana = df_movilidad[df_movilidad['TIPO_DIA'] == 'Laborable'].set_index('ID_ZONA')['VOLUMEN_TOTAL_PASAJEROS'].astype(int)
df_finde = df_movilidad[df_movilidad['TIPO_DIA'] == 'Fin de Semana'].set_index('ID_ZONA')['VOLUMEN_TOTAL_PASAJEROS'].astype(int)
df_estaciones = df_movilidad.groupby('ID_ZONA')['CANTIDAD_ESTACIONES'].max().astype(int)

#4.4 Consolidamos en un dataframe temporal con la nueva nomenclatura
df_movilidad_agrupado = pd.DataFrame({
    'MOV_DIA_SEMANA_PROMEDIO': df_semana,
    'MOV_FIN_DE_SEMANA_PROMEDIO': df_finde,
    'MOV_CANTIDAD_ESTACIONES': df_estaciones
}).reset_index()

# 4.5 Si las columnas ya existen en el master, la borramos antes de unir
columnas_movilidad = ['MOV_DIA_SEMANA_PROMEDIO', 'MOV_FIN_DE_SEMANA_PROMEDIO' , 'MOV_CANTIDAD_ESTACIONES']
for col in columnas_movilidad:
    if col in df_master.columns:
        df_master = df_master.drop(columns=[col])

# 4.6 Unión al Master
df_master = pd.merge(df_master, df_movilidad_agrupado, on='ID_ZONA', how='left')

print("-" * 70)
print(f"✅ MOVILIDAD integrada. Dimensiones del Master: {df_master.shape}")
print("-" * 70)
display(df_master.head())

----------------------------------------------------------------------
📊 Previsualización de MOVILIDAD:
----------------------------------------------------------------------

  ID_ZONA       TIPO_DIA  VOLUMEN_TOTAL_PASAJEROS  CANTIDAD_ESTACIONES
0  MN0101  Fin de Semana                    54974                   10
1  MN0101      Laborable                    78390                   10
2  MN0102  Fin de Semana                    36589                    6

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62 entries, 0 to 61
Data columns (total 4 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID_ZONA                  62 non-null     object
 1   TIPO_DIA                 62 non-null     object
 2   VOLUMEN_TOTAL_PASAJEROS  62 non-null     int64
 3   CANTIDAD_ESTACIONES      62 non-null     int64
dtypes: int64(2), object(2)
memory usage: 2.1+ KB

None

----------------------------------------------------------------------
✅ MOVILIDAD integrada. Dimensiones del Master: (38, 16)
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,SEG_DELITOS_OTROS,SEG_DELITOS_PROPIEDAD,SEG_DELITOS_TRANSPORTE,MOV_DIA_SEMANA_PROMEDIO,MOV_FIN_DE_SEMANA_PROMEDIO,MOV_CANTIDAD_ESTACIONES
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10,73.0,78.0,28.0,78390.0,54974.0,10.0
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41,116.0,77.0,13.0,58553.0,36589.0,6.0
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,NaN,NaN,NaN
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01,88.0,116.0,6.0,51431.0,39477.0,6.0
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61,93.0,80.0,16.0,30640.0,23725.0,4.0

In [21]:
#PASO 5: CARGA Y SELECCIÓN DEL DATASET RESTAURANTES

# 5.1 Carga del dataset con el nombre exacto
df_restaurantes = pd.read_csv(os.path.join(ruta_tablas, 'competencia', 'RESTAURANTES.csv'))

# 5.2 Visualización previa 
print("-" * 70)
print("📊 Previsualización de RESTAURANTES:")
print("-" * 70)
display(df_restaurantes.head(3))

# 5.3 Transformación: Convertimos las categorías en columnas independientes
df_res_pivot = df_restaurantes.pivot_table(
    index='ID_ZONA', 
    columns='CLASIFICACION_COMPETENCIA', 
    values='CANTIDAD_LOCALES', 
    aggfunc='sum'
).reset_index()

# 5.4 Renombrado para claridad en el Master
df_res_pivot.rename(columns={
    'Directa (Rivales)': 'RES_COM_DIRECTA',
    'Indirecta (Tráfico)': 'RES_COM_INDIRECTA'
}, inplace=True)

#5.5 Si las columnas ya existen en el master, la borramos antes de unir
columnas_res = ['RES_COM_DIRECTA', 'RES_COM_INDIRECTA']
for col in columnas_res:
    if col in df_master.columns:
        df_master = df_master.drop(columns=[col])

# 5.6 Unión al Master
df_master = pd.merge(df_master, df_res_pivot, on='ID_ZONA', how='left')

print("-" * 70)
print(f"✅ RESTAURANTES integrada. Dimensiones del Master: {df_master.shape}")
print("-" * 70)
display(df_master.head())

----------------------------------------------------------------------
📊 Previsualización de RESTAURANTES:
----------------------------------------------------------------------

  ID_ZONA         TIPO_COCINA CLASIFICACION_COMPETENCIA  CANTIDAD_LOCALES
0  MN0101            American       Indirecta (Tráfico)               160
1  MN0101  Asian/Asian Fusion       Indirecta (Tráfico)                13
2  MN0101             Chicken       Indirecta (Tráfico)                 3

----------------------------------------------------------------------
✅ RESTAURANTES integrada. Dimensiones del Master: (38, 18)
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,SEG_DELITOS_OTROS,SEG_DELITOS_PROPIEDAD,SEG_DELITOS_TRANSPORTE,MOV_DIA_SEMANA_PROMEDIO,MOV_FIN_DE_SEMANA_PROMEDIO,MOV_CANTIDAD_ESTACIONES,RES_COM_DIRECTA,RES_COM_INDIRECTA
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10,73.0,78.0,28.0,78390.0,54974.0,10.0,24.0,305.0
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41,116.0,77.0,13.0,58553.0,36589.0,6.0,11.0,150.0
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01,88.0,116.0,6.0,51431.0,39477.0,6.0,12.0,275.0
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61,93.0,80.0,16.0,30640.0,23725.0,4.0,15.0,242.0

In [22]:
#PASO 5: CARGA Y SELECCIÓN DEL DATASET LUGARES INTERES

# 6.1 Carga del dataset
df_lugares = pd.read_csv(os.path.join(ruta_tablas, 'lugares_interes', 'LUGARES_INTERES.csv'))

# 6.2 Visualización previa 
print("-" * 70)
print("📊 Previsualización de LUGARES DE INTERÉS:")
print("-" * 70)
display(df_lugares.head(15))


# 6.3 Re-clasificación de lugares de interes, según su comportamiento humano
mapa_final = {
    'Administracion Publica': 'LUG_OFICINAS_ESCUELAS',
    'Educacion': 'LUG_OFICINAS_ESCUELAS',
    'Comercial y Hoteles': 'LUG_COMERCIO_TURISMO',
    'Cultura': 'LUG_COMERCIO_TURISMO',
    'Monumentos y Plazas': 'LUG_COMERCIO_TURISMO',
    'Parques y Jardines': 'LUG_COMERCIO_TURISMO',
    'Residencial': 'LUG_RESIDENCIAL_EXCLUSIVO'  
}

# 6.4 Aplicación de la subcategoría
df_lugares['SUB_CATEGORIA'] = df_lugares['CATEGORIA_LUGAR'].map(mapa_final)

# 6.5 Agregación
df_lug_agrupado = df_lugares.groupby(['ID_ZONA', 'SUB_CATEGORIA'])['CANTIDAD_LUGARES'].sum().unstack(fill_value=0).reset_index()
       
# 6.6 Si las columnas ya existen en el master, la borramos antes de unir
columnas_lug = ['LUG_OFICINAS_ESCUELAS', 'LUG_COMERCIO_TURISMO', 'LUG_RESIDENCIAL_EXCLUSIVO']
for col in columnas_lug:
    if col in df_master.columns:
        df_master = df_master.drop(columns=[col])

# 6.7 Unión al Master
df_master = pd.merge(df_master, df_lug_agrupado, on='ID_ZONA', how='left')

print("-" * 70)
print(f"✅ LUGARES DE INTERÉS. Dimensiones del Master: {df_master.shape}")
print("-" * 70)
display(df_master.head())

----------------------------------------------------------------------
📊 Previsualización de LUGARES DE INTERÉS:
----------------------------------------------------------------------

   ID_ZONA         CATEGORIA_LUGAR  CANTIDAD_LUGARES
0   MN0101  Administracion Publica                12
1   MN0101     Comercial y Hoteles                41
2   MN0101                 Cultura                21
3   MN0101               Educacion                25
4   MN0101     Monumentos y Plazas                37
5   MN0101      Parques y Jardines                23
6   MN0101             Residencial                 6
7   MN0102  Administracion Publica                26
8   MN0102     Comercial y Hoteles                 3
9   MN0102                 Cultura                 2
10  MN0102               Educacion                16
11  MN0102     Monumentos y Plazas                 8
12  MN0102      Parques y Jardines                15
13  MN0102             Residencial                 1
14  MN0191  Administracion Publica                 2

----------------------------------------------------------------------
✅ LUGARES DE INTERÉS. Dimensiones del Master: (38, 21)
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,SEG_DELITOS_OTROS,SEG_DELITOS_PROPIEDAD,SEG_DELITOS_TRANSPORTE,MOV_DIA_SEMANA_PROMEDIO,MOV_FIN_DE_SEMANA_PROMEDIO,MOV_CANTIDAD_ESTACIONES,RES_COM_DIRECTA,RES_COM_INDIRECTA,LUG_COMERCIO_TURISMO,LUG_OFICINAS_ESCUELAS,LUG_RESIDENCIAL_EXCLUSIVO
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10,73.0,78.0,28.0,78390.0,54974.0,10.0,24.0,305.0,122,37,6
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41,116.0,77.0,13.0,58553.0,36589.0,6.0,11.0,150.0,28,42,1
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,30,3,0
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01,88.0,116.0,6.0,51431.0,39477.0,6.0,12.0,275.0,40,15,0
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61,93.0,80.0,16.0,30640.0,23725.0,4.0,15.0,242.0,38,94,1

In [23]:
#PASO 7: CARGA Y SELECCIÓN DEL DATASET COSTO_ALQUILER

# 7.1 Carga del dataset
df_alquiler = pd.read_csv(os.path.join(ruta_tablas, 'alquiler', 'COSTO_ALQUILER.csv'))

# 7.2 Visualización previa
print("-" * 70)
print("📊 Previsualización de COSTO ALQUILER:")
print("-" * 70)
display(df_alquiler.head(3))

# 7.3 Selección y Renombrado 
df_alquiler_sel = df_alquiler[['ID_ZONA', 'PRECIO_PIES_CUADRADOS_ANUAL']].copy()
df_alquiler_sel.rename(columns={'PRECIO_PIES_CUADRADOS_ANUAL': 'ALQ_PRECIO_PIE2_ANUAL'}, inplace=True)

# 7.4 Protección contra re-ejecución
if 'ALQ_PRECIO_PIE2_ANUAL' in df_master.columns:
    df_master = df_master.drop(columns=['ALQ_PRECIO_PIE2_ANUAL'])

# 7.5 Unión final al Master (Usamos left para mantener nuestras 31 zonas base)
df_master = pd.merge(df_master, df_alquiler_sel, on='ID_ZONA', how='left')

print("-" * 70)
print(f"✅ COSTO ALQUILER. Dimensiones del Master: {df_master.shape}")
print("-" * 70)
display(df_master.head())

----------------------------------------------------------------------
📊 Previsualización de COSTO ALQUILER:
----------------------------------------------------------------------

  ID_ZONA  PRECIO_PIES_CUADRADOS_ANUAL
0  MN0101                        91.91
1  MN0102                       122.72
2  MN0191                        61.00

----------------------------------------------------------------------
✅ COSTO ALQUILER. Dimensiones del Master: (38, 22)
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,SEG_DELITOS_OTROS,SEG_DELITOS_PROPIEDAD,SEG_DELITOS_TRANSPORTE,MOV_DIA_SEMANA_PROMEDIO,MOV_FIN_DE_SEMANA_PROMEDIO,MOV_CANTIDAD_ESTACIONES,RES_COM_DIRECTA,RES_COM_INDIRECTA,LUG_COMERCIO_TURISMO,LUG_OFICINAS_ESCUELAS,LUG_RESIDENCIAL_EXCLUSIVO,ALQ_PRECIO_PIE2_ANUAL
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10,73.0,78.0,28.0,78390.0,54974.0,10.0,24.0,305.0,122,37,6,91.91
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41,116.0,77.0,13.0,58553.0,36589.0,6.0,11.0,150.0,28,42,1,122.72
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,30,3,0,61.00
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01,88.0,116.0,6.0,51431.0,39477.0,6.0,12.0,275.0,40,15,0,190.54
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61,93.0,80.0,16.0,30640.0,23725.0,4.0,15.0,242.0,38,94,1,99.03

In [27]:
#PASO 7: DATASET MAESTRO 

import os

# 1. Ruta de la carpeta de destino
ruta_final = '../../datos/maestro'
nombre_archivo = 'MASTER_DATASET_MANHATTAN.csv'
ruta_completa = os.path.join(ruta_final, nombre_archivo)

# 2. Exportamos el DataFrame 
df_master.to_csv(ruta_completa, index=False)

print("-" * 70)
print(f"📁 ARCHIVO EXPORTADO EXITOSAMENTE")
print(f"📍 Ubicación: {ruta_completa}")
print(f"📊 Estado: {df_master.shape[0]} filas y {df_master.shape[1]} columnas.")
print("-" * 70)

# 3. Visualización 
display(df_master)

----------------------------------------------------------------------
📁 ARCHIVO EXPORTADO EXITOSAMENTE
📍 Ubicación: Dataset_Final\MASTER_DATASET_MANHATTAN.csv
📊 Estado: 38 filas y 22 columnas.
----------------------------------------------------------------------

,ID_ZONA,NOMBRE_ZONA,AREA_KM2,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,SEG_DELITOS_OTROS,SEG_DELITOS_PROPIEDAD,SEG_DELITOS_TRANSPORTE,MOV_DIA_SEMANA_PROMEDIO,MOV_FIN_DE_SEMANA_PROMEDIO,MOV_CANTIDAD_ESTACIONES,RES_COM_DIRECTA,RES_COM_INDIRECTA,LUG_COMERCIO_TURISMO,LUG_OFICINAS_ESCUELAS,LUG_RESIDENCIAL_EXCLUSIVO,ALQ_PRECIO_PIE2_ANUAL
0,MN0101,Financial District-Battery Park City,19.2268,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.10,73.0,78.0,28.0,78390.0,54974.0,10.0,24.0,305.0,122,37,6,91.91
1,MN0102,Tribeca-Civic Center,13.5782,23257.0,36.8,185902.0,68.92,2.20,873.0,81.41,116.0,77.0,13.0,58553.0,36589.0,6.0,11.0,150.0,28,42,1,122.72
2,MN0191,The Battery-Governors Island-Ellis Island-Libe...,11.9933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,3.0,NaN,NaN,NaN,NaN,NaN,30,3,0,61.00
3,MN0201,SoHo-Little Italy-Hudson Square,12.9168,22167.0,39.3,132900.0,70.97,1.78,975.0,82.01,88.0,116.0,6.0,51431.0,39477.0,6.0,12.0,275.0,40,15,0,190.54
4,MN0202,Greenwich Village,10.6005,31517.0,35.7,174062.0,64.44,1.74,1003.0,78.61,93.0,80.0,16.0,30640.0,23725.0,4.0,15.0,242.0,38,94,1,99.03
5,MN0203,West Village,14.4169,32518.0,39.7,168629.0,71.17,1.68,2364.0,80.94,74.0,101.0,17.0,19220.0,16016.0,3.0,18.0,285.0,33,15,0,220.81
6,MN0301,Chinatown-Two Bridges,11.5416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.0,42.0,3.0,8089.0,7408.0,1.0,6.0,195.0,38,20,35,61.80
7,MN0302,Lower East Side,16.4732,46107.0,42.2,58841.0,53.27,2.05,12016.0,90.54,211.0,72.0,9.0,30606.0,25371.0,3.0,14.0,218.0,51,24,79,107.90
8,MN0303,East Village,18.9848,68412.0,33.9,76136.0,60.06,1.83,11928.0,91.01,146.0,134.0,4.0,21168.0,18699.0,2.0,32.0,427.0,83,42,74,127.58
9,MN0401,Chelsea-Hudson Yards,29.6718,61878.0,39.2,126272.0,70.06,1.67,6004.0,83.90,188.0,224.0,17.0,65068.0,48740.0,6.0,24.0,354.0,69,30,26,63.64
10,MN0402,Hell's Kitchen,18.3823,55221.0,39.1,105839.0,69.45,1.61,6556.0,87.46,282.0,136.0,44.0,12340.0,10763.0,2.0,36.0,320.0,49,31,9,126.14
11,MN0501,Midtown South-Flatiron-Union Square,14.8790,29670.0,35.2,182280.0,70.16,1.65,1493.0,82.85,191.0,255.0,36.0,123072.0,83012.0,9.0,26.0,495.0,54,37,0,68.50
12,MN0502,Midtown-Times Square,24.5525,21949.0,42.8,148446.0,65.59,1.61,1069.0,67.98,317.0,430.0,41.0,143758.0,116060.0,10.0,53.0,887.0,229,52,7,199.67
13,MN0601,Stuyvesant Town-Peter Cooper Village,5.5756,21963.0,39.6,160855.0,65.61,2.05,1097.0,92.47,25.0,18.0,1.0,NaN,NaN,NaN,1.0,4.0,4,0,57,140.00
14,MN0602,Gramercy,7.5260,26523.0,35.2,153720.0,68.32,1.71,849.0,78.79,55.0,56.0,4.0,15133.0,10721.0,2.0,13.0,148.0,22,37,0,138.33
15,MN0603,Murray Hill-Kips Bay,15.7712,54905.0,34.3,141463.0,71.82,1.70,2830.0,82.93,120.0,96.0,16.0,NaN,NaN,NaN,9.0,174.0,54,106,18,190.00
16,MN0604,East Midtown-Turtle Bay,13.1381,41969.0,45.6,170196.0,66.63,1.78,1721.0,73.04,45.0,68.0,17.0,39188.0,27418.0,2.0,17.0,315.0,54,127,6,220.00
17,MN0661,United Nations,1.0912,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,6,0,210.00
18,MN0701,Upper West Side-Lincoln Square,15.7974,68212.0,43.2,164712.0,64.80,1.81,3982.0,80.10,82.0,87.0,6.0,49653.0,32314.0,3.0,5.0,109.0,66,47,28,110.00
19,MN0702,Upper West Side (Central),25.4107,99128.0,44.9,159333.0,64.59,2.03,7618.0,81.00,121.0,104.0,6.0,33442.0,28979.0,3.0,15.0,168.0,50,50,71,101.77
20,MN0703,Upper West Side-Manhattan Valley,13.2005,51421.0,40.5,100165.0,58.99,2.14,9724.0,88.57,96.0,91.0,5.0,16214.0,12002.0,3.0,10.0,79.0,30,16,32,165.00
21,MN0801,Upper East Side-Lenox Hill-Roosevelt Island,21.5010,79296.0,37.9,137355.0,67.99,1.87,2959.0,77.43,74.0,68.0,1.0,24128.0,24025.0,4.0,18.0,174.0,39,76,8,184.09
22,MN0802,Upper East Side-Carnegie Hill,20.0654,54062.0,50.0,171961.0,59.30,2.01,2153.0,70.43,63.0,138.0,8.0,83903.0,44864.0,6.0,4.0,203.0,40,69,6,200.00
23,MN0803,Upper East Side-Yorkville,13.6450,78950.0,42.2,147475.0,65.92,1.84,4723.0,85.55,75.0,67.0,2.0,10750.0,10370.0,1.0,13.0,127.0,19,22,7,170.00
24,MN0901,Morningside Heights,15.9228,37984.0,28.1,87452.0,52.24,2.12,4722.0,85.07,80.0,29.0,5.0,28325.0,19214.0,3.0,5.0,58.0,24,93,18,76.36
25,MN0902,Manhattanville-West Harlem,10.7348,22260.0,34.5,46819.0,52.18,2.58,9922.0,90.95,126.0,30.0,2.0,9269.0,4967.0,2.0,7.0,24.0,20,36,15,55.36
26,MN0903,Hamilton Heights-Sugar Hill,15.9836,52530.0,38.0,68527.0,61.43,2.62,19999.0,91.20,163.0,59.0,5.0,16225.0,12979.0,3.0,15.0,66.0,53,9,1,95.00
27,MN1001,Harlem (South),14.4264,48803.0,38.3,74007.0,63.21,2.25,6565.0,87.75,227.0,82.0,20.0,22574.0,19445.0,5.0,8.0,52.0,29,35,20,70.00
28,MN1002,Harlem (North),23.7929,86090.0,38.1,51386.0,54.55,2.26,18165.0,91.05,483.0,132.0,5.0,8831.0,6244.0,4.0,4.0,51.0,50,35,108,110.00
29,MN1101,East Harlem (South),16.6539,58607.0,37.8,42076.0,49.85,2.14,19369.0,89.23,328.0,99.0,7.0,20813.0,11699.0,3.0,24.0,74.0,29,46,90,240.67
30,MN1102,East Harlem (North),26.1193,63526.0,36.6,39957.0,51.04,2.19,21871.0,90.91,440.0,142.0,13.0,19565.0,12042.0,2.0,32.0,77.0,58,43,90,100.00
31,MN1191,Randall's Island,23.4665,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.0,2.0,0.0,NaN,NaN,NaN,NaN,2.0,144,2,1,75.00
32,MN1201,Washington Heights (South),21.0277,74814.0,38.4,56929.0,53.39,2.63,41937.0,92.39,277.0,92.0,6.0,21219.0,15837.0,4.0,36.0,69.0,31,35,22,124.13
33,MN1202,Washington Heights (North),24.7735,75554.0,40.0,78465.0,60.63,2.53,37752.0,93.98,211.0,93.0,1.0,19029.0,16094.0,6.0,38.0,64.0,60,34,0,95.00
34,MN1203,Inwood,14.4369,38209.0,38.5,68523.0,63.16,2.51,23226.0,93.25,155.0,45.0,5.0,9223.0,7311.0,4.0,41.0,44.0,24,23,19,49.27
35,MN1291,Highbridge Park,7.7513,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.0,3.0,1.0,NaN,NaN,NaN,NaN,NaN,37,0,0,87.00
36,MN1292,Inwood Hill Park,10.0075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.0,5.0,0.0,NaN,NaN,NaN,NaN,NaN,41,3,1,80.00
37,MN6491,Central Park,38.3124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,31.0,2.0,2.0,37713.0,31878.0,5.0,NaN,7.0,162,0,0,230.00

In [26]:
#PASO 7: DATASET CONSOLIDADO ORIGINAL

import os
import pandas as pd

# 1. Aseguramos las rutas
ruta_tablas = '../../datos/base_datos'
ruta_final = '../../datos/maestro'

# 2. Definimos los archivos .csv que existen en las subcarpetas de base_datos
archivos_reales = [
    os.path.join(ruta_tablas, 'zonas', 'ZONAS.csv'),
    os.path.join(ruta_tablas, 'censo', 'CENSO.csv'),
    os.path.join(ruta_tablas, 'seguridad', 'SEGURIDAD.csv'),
    os.path.join(ruta_tablas, 'movilidad', 'MOVILIDAD.csv'),
    os.path.join(ruta_tablas, 'competencia', 'RESTAURANTES.csv'),
    os.path.join(ruta_tablas, 'lugares_interes', 'LUGARES_INTERES.csv'),
    os.path.join(ruta_tablas, 'alquiler', 'COSTO_ALQUILER.csv')
]

print("-" * 70)
print(f"📁 Archivos encontrados en datos/base_datos: {archivos_reales}")
print("-" * 70)

# 3. Usamos el primer archivo de la lista como base
if len(archivos_reales) > 0:
    # Cargamos el primero
    df_revision = pd.read_csv(archivos_reales[0])

    # 4. Unimos el resto
    for archivo in archivos_reales[1:]:
        df_temp = pd.read_csv(archivo)
        # Unimos por ID_ZONA con 'outer' para no perder nada de información bruta
        df_revision = pd.merge(df_revision, df_temp, on='ID_ZONA', how='outer')

    # 5. Exportación a la carpeta de revisión
    if not os.path.exists(ruta_final):
        os.makedirs(ruta_final)

    ruta_revision = os.path.join(ruta_final, 'DATASET_REVISION_TOTAL.csv')
    df_revision.to_csv(ruta_revision, index=False)

    print(f"✅ DATASET DE REVISIÓN GENERADO")
    print(f"📊 Columnas totales: {df_revision.shape[1]}")
    print(f"📈 Filas totales (formato largo): {df_revision.shape[0]}")
    print(f"📍 Guardado en: {ruta_revision}")
else:
    print("❌ Error: No se encontraron archivos CSV en la carpeta especificada.")

print("-" * 70)
display(df_revision.head())

----------------------------------------------------------------------
📁 Archivos encontrados en Tablas_SQL: ['CENSO.csv', 'COSTO_ALQUILER.csv', 'LUGARES_INTERES.csv', 'MOVILIDAD.csv', 'RESTAURANTES.csv', 'SEGURIDAD.csv', 'ZONAS.csv']
----------------------------------------------------------------------
✅ DATASET DE REVISIÓN GENERADO
📊 Columnas totales: 23
📈 Filas totales (formato largo): 126325
📍 Guardado en: Dataset_Final\DATASET_REVISION_TOTAL.csv
----------------------------------------------------------------------

,ID_ZONA,POBLACION_TOTAL,EDAD_MEDIANA,INGRESO_MEDIANO_HOGAR,TASA_EMPLEO,TAMANO_HOGAR_PROMEDIO,POBLACION_HISPANA,TASA_OCUPACION,PRECIO_PIES_CUADRADOS_ANUAL,CATEGORIA_LUGAR,CANTIDAD_LUGARES,TIPO_DIA,VOLUMEN_TOTAL_PASAJEROS,CANTIDAD_ESTACIONES,TIPO_COCINA,CLASIFICACION_COMPETENCIA,CANTIDAD_LOCALES,TIPO_DELITO,LUGAR_DELITO,CANTIDAD_INCIDENTES,NOMBRE_ZONA,NOMBRE_DISTRITO,AREA_KM2
0,MN0101,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.1,91.91,Administracion Publica,12,Fin de Semana,54974.0,10.0,American,Indirecta (Tráfico),160.0,ASALTO GRAVE,EDIFICIOS PUBLICOS,6.0,Financial District-Battery Park City,Manhattan,19.2268
1,MN0101,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.1,91.91,Administracion Publica,12,Fin de Semana,54974.0,10.0,American,Indirecta (Tráfico),160.0,ASALTO GRAVE,LOCAL COMERCIAL,7.0,Financial District-Battery Park City,Manhattan,19.2268
2,MN0101,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.1,91.91,Administracion Publica,12,Fin de Semana,54974.0,10.0,American,Indirecta (Tráfico),160.0,ASALTO GRAVE,OTROS,6.0,Financial District-Battery Park City,Manhattan,19.2268
3,MN0101,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.1,91.91,Administracion Publica,12,Fin de Semana,54974.0,10.0,American,Indirecta (Tráfico),160.0,ASALTO GRAVE,TRANSPORTE,18.0,Financial District-Battery Park City,Manhattan,19.2268
4,MN0101,48608.0,34.3,198961.0,79.57,1.99,1639.0,83.1,91.91,Administracion Publica,12,Fin de Semana,54974.0,10.0,American,Indirecta (Tráfico),160.0,ASALTO GRAVE,VIA PUBLICA,23.0,Financial District-Battery Park City,Manhattan,19.2268